/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.farmerRole;

import business.Business;
import business.Idea.Idea;
import business.enterprise.Enterprise;
import business.enterprise.KnowledgeTransferEnterprise;
import business.feedback.Feedback;
import business.network.Network;
import business.organization.Organization;
import business.organization.VolunteersOrganization;
import business.products.Product;
import business.userAccount.UserAccount;
import business.workQueue.VolunteerRequest;
import business.workQueue.WorkRequest;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author bhavanidevulapalli
 */
public class FarmersDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmersDashboardJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Business business;
    private Network network;
    private Enterprise enterprise;
    private WorkRequest request;
    private boolean view = false;
    private boolean licenPlateCaptured = false;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon productImage;
    ImageIcon ideaImage;
    // private Product product;

    public FarmersDashboardJPanel(JPanel userProcessContainer, UserAccount account, Business business, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.network = network;
        this.enterprise = enterprise;

        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png", "png");

        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
        String userName = account.getUsername();
        txtFarmersUserName.setText(userName);
        
         
        txtFarmersName.setText(userName);
        txtLocation.setText(account.getPerson().getaddress());
        
        System.out.println(userName);
        populateTable(userName);

        Feedbacks.setVisible(false);

        setupTableTextWrap();

        populateIdeaTable();
        ViewRequest.setVisible(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        tblViewIdea.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewIdeaMouseClicked(evt);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prodImg = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAttach = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        ComboCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblExistingBalance = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        txtUserNamewallet = new javax.swing.JTextField();
        txtExistingBalance = new javax.swing.JTextField();
        AddAmount = new javax.swing.JPanel();
        lblAddbalance = new javax.swing.JLabel();
        txtAddAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Blog = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnGetFeedback = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblViewIdea = new javax.swing.JTable();
        Feedbacks = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        feedbackScroll1 = new javax.swing.JScrollPane();
        tblViewFeedback = new javax.swing.JTable();
        View = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        updateDescription = new javax.swing.JTextField();
        ideaImg = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        txtTitle1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        updateDescription1 = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ViewProducts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        ViewRequest = new javax.swing.JPanel();
        lbProductID = new javax.swing.JLabel();
        OfferedPrice = new javax.swing.JLabel();
        lblestimationPirce = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        txtReject = new javax.swing.JButton();
        txtProductID = new javax.swing.JTextField();
        TxtofferedPrice = new javax.swing.JTextField();
        txtActualPrice = new javax.swing.JTextField();
        UpdateDescriptionmessage = new javax.swing.JTextField();
        lblComments1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtFarmersName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMEssage = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtFarmersUserName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));

        header.setBackground(new java.awt.Color(0, 80, 84));
        header.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(204, 255, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-field-and-tractor-48.png"))); // NOI18N
        header.setText("Farmers Work Area");

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 238, 231));

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        txtName.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Category:");

        lblImg.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblImg.setText("Image:");

        jLabel4.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Price:");

        prodImg.setBackground(new java.awt.Color(255, 255, 255));
        prodImg.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        prodImg.setText("<No Image>");
        prodImg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        prodImg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtPrice.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        btnAttach.setBackground(new java.awt.Color(0, 102, 102));
        btnAttach.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        btnAttach.setForeground(new java.awt.Color(204, 238, 231));
        btnAttach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-add-image-30.png"))); // NOI18N
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Quantity:");

        btnRemove.setBackground(new java.awt.Color(0, 102, 102));
        btnRemove.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(204, 238, 231));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-remove-image-30.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Description:");

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(204, 238, 231));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-add-30.png"))); // NOI18N
        btnAdd.setText("Add Product");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lbl.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lbl.setText("/ lb");

        lbl1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lbl1.setText("lb(s)");

        ComboCategory.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        ComboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetable", "Fruit", "Dairy", "Meat", "Grains", "Poultry", "Honey", "Herbs and Spices", "Others" }));
        ComboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCategoryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/view.png"))); // NOI18N
        jLabel1.setText("Add Products");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/77JTresize.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(ComboCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(prodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRemove)
                                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrice)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl1)))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(ComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodImg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addGap(309, 309, 309))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Add Products", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        lblName.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 204));
        lblName.setText("Name:");

        lblExistingBalance.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblExistingBalance.setForeground(new java.awt.Color(255, 255, 204));
        lblExistingBalance.setText("Existing Balance");

        btnAdd1.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd1.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(0, 102, 153));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-add-dollar-40.png"))); // NOI18N
        btnAdd1.setText("Add Money");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        txtUserNamewallet.setEditable(false);
        txtUserNamewallet.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        txtExistingBalance.setEditable(false);
        txtExistingBalance.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        AddAmount.setBackground(new java.awt.Color(255, 255, 204));

        lblAddbalance.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblAddbalance.setText("Amount:");

        txtAddAmount.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(0, 102, 153));
        btnSubmit.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 204));
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-submit-30.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddAmountLayout = new javax.swing.GroupLayout(AddAmount);
        AddAmount.setLayout(AddAmountLayout);
        AddAmountLayout.setHorizontalGroup(
            AddAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAmountLayout.createSequentialGroup()
                .addGroup(AddAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddAmountLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblAddbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddAmountLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        AddAmountLayout.setVerticalGroup(
            AddAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddAmountLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddbalance)
                    .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSubmit)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        lblTitle1.setFont(new java.awt.Font("Khmer MN", 1, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 204));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-digital-wallet-70.png"))); // NOI18N
        lblTitle1.setText(" Load Wallet");
        lblTitle1.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/productImages/wallet.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExistingBalance)
                            .addComponent(lblName))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserNamewallet, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtExistingBalance)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(AddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnAdd1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(txtUserNamewallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExistingBalance)
                            .addComponent(txtExistingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(btnAdd1)
                        .addGap(30, 30, 30)
                        .addComponent(AddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Wallet", jPanel3);

        Blog.setBackground(new java.awt.Color(202, 224, 240));
        Blog.setPreferredSize(new java.awt.Dimension(1100, 750));

        btnSearch.setBackground(new java.awt.Color(0, 80, 84));
        btnSearch.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(204, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/search-30.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(0, 80, 84));
        txtSearch.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(204, 255, 255));
        txtSearch.setText("Enter Id or title");

        btnGetFeedback.setBackground(new java.awt.Color(0, 80, 84));
        btnGetFeedback.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnGetFeedback.setForeground(new java.awt.Color(204, 255, 255));
        btnGetFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-feedback-30.png"))); // NOI18N
        btnGetFeedback.setText("Click me!!");
        btnGetFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetFeedbackActionPerformed(evt);
            }
        });

        tblViewIdea.setBackground(new java.awt.Color(179, 212, 197));
        tblViewIdea.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        tblViewIdea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Title", "Description", "Image", "Created Date", "Full name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblViewIdea);

        Feedbacks.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(202, 224, 240));

        tblViewFeedback.setBackground(new java.awt.Color(179, 212, 197));
        tblViewFeedback.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        tblViewFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Provided By:", "Feedback", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewFeedback.setGridColor(new java.awt.Color(0, 102, 102));
        feedbackScroll1.setViewportView(tblViewFeedback);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feedbackScroll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(feedbackScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Feedbacks.addTab("Feedbacks ", jPanel2);

        View.setBackground(new java.awt.Color(179, 212, 197));

        txtTitle.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        txtTitle.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Title:");

        jLabel9.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Description:");

        updateDescription.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        updateDescription.setEnabled(false);
        jScrollPane3.setViewportView(updateDescription);

        ideaImg.setBackground(new java.awt.Color(255, 255, 255));
        ideaImg.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        ideaImg.setText("<No Image>");
        ideaImg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ideaImg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ideaImg.setMaximumSize(new java.awt.Dimension(73, 19));
        ideaImg.setMinimumSize(new java.awt.Dimension(73, 19));
        ideaImg.setPreferredSize(new java.awt.Dimension(73, 19));

        lblImg1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblImg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImg1.setText("Image:");

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ideaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(564, 564, Short.MAX_VALUE))
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(ViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewLayout.createSequentialGroup()
                                .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ideaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        Feedbacks.addTab("View Idea", View);

        add.setBackground(new java.awt.Color(179, 212, 197));

        txtTitle1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Idea Title:");

        jLabel11.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Feedback:");

        updateDescription1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(updateDescription1);

        btnSave1.setBackground(new java.awt.Color(0, 80, 84));
        btnSave1.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(204, 255, 255));
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-facebook-like-30.png"))); // NOI18N
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave1)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11)
                        .addContainerGap(387, Short.MAX_VALUE))
                    .addGroup(addLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Feedbacks.addTab("Add Feedback", add);

        jLabel13.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        jLabel13.setText("to look at feedback, view idea and add feedback");

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-ideas-50.png"))); // NOI18N
        jLabel12.setText("Blog Posts");

        javax.swing.GroupLayout BlogLayout = new javax.swing.GroupLayout(Blog);
        Blog.setLayout(BlogLayout);
        BlogLayout.setHorizontalGroup(
            BlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlogLayout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9)
                .addContainerGap())
            .addGroup(BlogLayout.createSequentialGroup()
                .addGap(578, 578, 578)
                .addComponent(btnGetFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(BlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        BlogLayout.setVerticalGroup(
            BlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(BlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Blog", Blog);

        ViewProducts.setBackground(new java.awt.Color(0, 113, 178));

        tblView.setBackground(new java.awt.Color(204, 255, 255));
        tblView.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name ", "Price", "Quantity", "Estimation Total Cost", "Image", "ReviewStatus", "OfferedPrice", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(tblView);

        jLabel7.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/view.png"))); // NOI18N
        jLabel7.setText("View Products");

        jButton1.setText("jButton1");

        btnView.setBackground(new java.awt.Color(255, 204, 204));
        btnView.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/view.png"))); // NOI18N
        btnView.setText("View Request");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        ViewRequest.setBackground(new java.awt.Color(204, 255, 255));

        lbProductID.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lbProductID.setText("ProductID:");

        OfferedPrice.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        OfferedPrice.setText("OfferedPrice:");

        lblestimationPirce.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblestimationPirce.setText("My Price:");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        txtReject.setText("Reject");
        txtReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRejectActionPerformed(evt);
            }
        });

        txtProductID.setEditable(false);

        TxtofferedPrice.setEditable(false);

        UpdateDescriptionmessage.setEnabled(false);

        lblComments1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblComments1.setText("Comments :");

        javax.swing.GroupLayout ViewRequestLayout = new javax.swing.GroupLayout(ViewRequest);
        ViewRequest.setLayout(ViewRequestLayout);
        ViewRequestLayout.setHorizontalGroup(
            ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewRequestLayout.createSequentialGroup()
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewRequestLayout.createSequentialGroup()
                        .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewRequestLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblComments1)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewRequestLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbProductID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OfferedPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblestimationPirce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)))
                        .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtActualPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtProductID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtofferedPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateDescriptionmessage)))
                    .addGroup(ViewRequestLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnAccept)
                        .addGap(18, 18, 18)
                        .addComponent(txtReject)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewRequestLayout.setVerticalGroup(
            ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProductID)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfferedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtofferedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblestimationPirce)
                    .addComponent(txtActualPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComments1)
                    .addComponent(UpdateDescriptionmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(txtReject))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout ViewProductsLayout = new javax.swing.GroupLayout(ViewProducts);
        ViewProducts.setLayout(ViewProductsLayout);
        ViewProductsLayout.setHorizontalGroup(
            ViewProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewProductsLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(ViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewProductsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(88, 88, 88))
            .addGroup(ViewProductsLayout.createSequentialGroup()
                .addGroup(ViewProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        ViewProductsLayout.setVerticalGroup(
            ViewProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewProductsLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ViewProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewProductsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnView))
                    .addGroup(ViewProductsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(228, 228, 228)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Products", ViewProducts);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        lblUsername.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        lblUsername.setText("FarmerName");

        jLabel16.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel16.setText("Message");

        txtMEssage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMEssageActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        jButton2.setText("Raise Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel17.setText("Location");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtMEssage)
                            .addComponent(txtFarmersName)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtFarmersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMEssage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VolunteerRequest", jPanel5);

        txtFarmersUserName.setBackground(new java.awt.Color(204, 255, 255));
        txtFarmersUserName.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFarmersUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFarmersUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(header))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewIdeaMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tblViewIdea.getSelectedRow();
        if (selectedRow >= 0) {
            Feedbacks.setVisible(false);
        }
    }

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                productImage = new ImageIcon(url);
                productImage = new ImageIcon(productImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));

                prodImg.setIcon(productImage);
            } catch (MalformedURLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to load image", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void populateTable(String userId) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        ArrayList<UserAccount> userList = business.getUserAccountDirectory().getUserAccountList();
        // Set<Integer> addedProductIds = new HashSet<>();
        for (UserAccount user : userList) {

            Object[] row = new Object[10];
            ArrayList<Product> productList = business.getProductDirectory().getProductList();
            for (Product product : productList) {
                if (null != user.getUsername() && userId.equalsIgnoreCase(user.getUsername()) && product.getFarmersId().equalsIgnoreCase(user.getUsername())) {
                    String productName = product.getName();
                    int productId = product.getProductId();
                    double price = product.getPrice();
                    int quantity = product.getQuantity();
                    double EstimationCost = business.getProductDirectory().calculateEstimationCost(price, quantity);
//if (!addedProductIds.contains(productId)){
                    row[0] = productId;
                    row[1] = productName;
                    row[2] = price;
                    row[3] = quantity;
                    row[4] = EstimationCost;
                    row[5] = product.getImage();
                    row[6] = product.getStatus();
                    Product.Status status1 = product.getStatus();

                    // Check if the status is "reviewed"
                    // if (status1 == Product.Status.REVIEWED) {
                    row[7] = (product.getOfferedPrice() == 0.00) ? "TBD" : product.getOfferedPrice();
                    row[8] = product.getDescription();
                    //  }
                    model.addRow(row);
                    tblView.setRowHeight(150);
                    // addedProductIds.add(productId);
                    // }
                }
            }
        }
        tblView.getColumnModel().getColumn(5).setCellRenderer(new ImageRenderer());
        tblView.setModel(model);
        tblView.setPreferredScrollableViewportSize(new Dimension(tblView.getPreferredScrollableViewportSize().width, 150));
        tblView.revalidate();
    }

    private class ImageRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            //ImageIcon imageIcon = new ImageIcon(product.getImage().getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            ImageIcon imageIcon = new ImageIcon(((ImageIcon) value).getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            return new JLabel(imageIcon);
        }
    }
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        productImage = null;
        prodImg.setIcon(productImage);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        if (txtName.getText().isEmpty() || txtPrice.getText().isEmpty() || txtQuantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate numeric input for price
        double price;
        try {
            price = Double.parseDouble(txtPrice.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate integer input for quantity
        int quantity;
        try {
            quantity = Integer.parseInt(txtQuantity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be an integer value.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate image attachment
        if (productImage == null) {
            JOptionPane.showMessageDialog(this, "Please attach an image for the product.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int productId = business.getProductDirectory().getProductList().size() + 1;

        String name = txtName.getText();
        String category = ComboCategory.getSelectedItem().toString();
        String description = txtDescription.getText();
        String userName = txtFarmersUserName.getText();

        System.out.println(business.getProductDirectory().getProductList().size());
        Product product = new Product(name, category, price, quantity, description, productImage, userName, Product.Status.TO_BE_REVIEWED, Double.valueOf("0.0"));

        business.getProductDirectory().addProduct(product);

        JOptionPane.showMessageDialog(this, "Product added successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);

        txtName.setText("");
        ComboCategory.setSelectedIndex(0);
        txtPrice.setText("");
        txtQuantity.setText("");
        txtDescription.setText("");
        prodImg.setText(" ");
        populateTable(account.getUsername());
    }//GEN-LAST:event_btnAddActionPerformed

    private void ComboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCategoryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearch.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblViewIdea.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Idea idea : business.getIdeaDirectory().getIdeaList()) {

            if ((Integer.toString(idea.getIdeaId()).contains(searchText)
                    || idea.getTitle().toLowerCase().contains(searchText))) {

                // Add the idea to the table
                ImageIcon icon = idea.getIdeaImage();
                if (icon != null) {
                    // Scale the icon if necessary
                    Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                    icon = new ImageIcon(image);
                }

                model.addRow(new Object[]{
                    idea.getIdeaId(),
                    idea.getTitle(),
                    idea.getDescription(),
                    icon,
                    formatDate(idea.getCreatedDate())
                });
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGetFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetFeedbackActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewIdea.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                int ideaId = Integer.parseInt(tblViewIdea.getValueAt(selectedRow, 0).toString());
                populateFeedbackTable(ideaId);
                Feedbacks.setVisible(true);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error parsing idea ID from the selected row.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an idea to view feedback.");
        }
    }//GEN-LAST:event_btnGetFeedbackActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        if (updateDescription1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int selectedRow = tblViewIdea.getSelectedRow();
        int ideaId = Integer.parseInt(tblViewIdea.getValueAt(selectedRow, 0).toString());
        Idea existingIdea = business.getIdeaDirectory().getIdeaById(ideaId);
        String author = account.getPerson().getFirstName() + " " + account.getPerson().getLastName();

        if (existingIdea != null) {
            txtTitle1.setText(existingIdea.getTitle());
        }

        String details = updateDescription1.getText();

        int lastfeedId = 0;
        for (Feedback feedback : business.getFeedbackDirectory().getFeedbackList()) {
            if (feedback.getFeedId() > lastfeedId) {
                lastfeedId = feedback.getFeedId();
            }
        }
        int feedId = lastfeedId + 1;

        Feedback feedback = new Feedback(feedId, ideaId, details, author, account.getPerson().getPersonId());

        business.getFeedbackDirectory().addFeed(feedback);

        JOptionPane.showMessageDialog(this, "Feedback added successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);

        // Clear the form fields
        txtTitle1.setText("");
        updateDescription1.setText("");
        populateFeedbackTable(ideaId);

    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        AddAmount.setVisible(true);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtAddAmount.getText() == null) {
            JOptionPane.showMessageDialog(this, "Please enter the amount you want to add");
        } else {
            account.getPerson().getWallet().addFunds(Double.valueOf(txtAddAmount.getText()));
            txtExistingBalance.setText(String.valueOf(account.getPerson().getWallet().getBalance()));
            AddAmount.setVisible(false);

        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblView.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
         int productID = (int) tblView.getValueAt(selectedRow, 0);
         txtProductID.setText(String.valueOf(productID));
        Product product = business.getProductDirectory().getProductFromProductID(productID);
         String status=String.valueOf(tblView.getValueAt(selectedRow, 6));

      if(status.equalsIgnoreCase("AWAITING_FARMER_APPROVAL"))
      {
        ViewRequest.setVisible(true);
        Double price = (Double) tblView.getValueAt(selectedRow, 2);
       
        String Description = String.valueOf(tblView.getValueAt(selectedRow, 8));
        UpdateDescriptionmessage.setText(Description);

        TxtofferedPrice.setText(Double.valueOf(product.getOfferedPrice()).toString());
        txtActualPrice.setText(String.valueOf(price));
      }
      else
      {
          JOptionPane.showMessageDialog(this, "Please wait for the Quality Specialist to pick your request.", "Warning", JOptionPane.INFORMATION_MESSAGE);
      }
      
        


    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int productID = Integer.valueOf(txtProductID.getText());

        Product productFromProductID = business.getProductDirectory().getProductFromProductID(productID);

        productFromProductID.setDescription(UpdateDescriptionmessage.getText());
        productFromProductID.setStatus(Product.Status.REVIEWED);

        productFromProductID.setOfferedPrice(Double.valueOf(TxtofferedPrice.getText()));
        
         JOptionPane.showMessageDialog(this, "The product is now available for purchase. Thank you for your interest!", "Success", JOptionPane.INFORMATION_MESSAGE);
         ViewRequest.setVisible(false);
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void txtRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRejectActionPerformed
        // TODO add your handling code here:
         int productID = Integer.valueOf(txtProductID.getText());
         Product productFromProductID = business.getProductDirectory().getProductFromProductID(productID);
         business.getProductDirectory().removeProduct(productFromProductID);
          ViewRequest.setVisible(false);
           JOptionPane.showMessageDialog(this, "you have rejected the offer. The product has been removed from the list. If you need help reach out to the team.", "Offer Rejected", JOptionPane.INFORMATION_MESSAGE);
                                           
    }//GEN-LAST:event_txtRejectActionPerformed

    private void txtMEssageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMEssageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMEssageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        VolunteerRequest Request = new VolunteerRequest();
        txtFarmersUserName.setText(account.getUsername());
        txtLocation.setText(account.getPerson().getaddress());
        Request.setMessage(txtMEssage.getText());
        Request.setSender(account);
        Request.setLocation(txtLocation.getText());
        Request.setRequestDate(new Date());
        Request.setStatus("RequestRaised");
        

        ArrayList<Network> networkList = business.getNetworkList();
        for (Network network : networkList) {
            ArrayList<Enterprise> enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise enterprise : enterpriseList) {
                if (enterprise instanceof KnowledgeTransferEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganisationList()) {
                        if (organization instanceof VolunteersOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(Request);
                            account.getWorkQueue().getWorkRequestList().add(Request);
                            System.out.println(organization.getWorkQueue().getWorkRequestList().size());
                            JOptionPane.showMessageDialog(this, "Request Successfully raised", "Success", JOptionPane.INFORMATION_MESSAGE);
                            break;
                        }
                    }
                }
            }
        }
        txtFarmersUserName.setText(" ");
        txtLocation.setText(" ");
        txtMEssage.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    public void populateIdeaTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewIdea.getModel();
        model.setRowCount(0);

        for (Idea idea : business.getIdeaDirectory().getIdeaList()) {
            ImageIcon icon = idea.getIdeaImage();
            if (icon != null) {
                // Scale the icon if necessary
                Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                icon = new ImageIcon(image);
            }

            model.addRow(new Object[]{
                idea.getIdeaId(),
                idea.getTitle(),
                idea.getDescription(),
                icon,
                formatDate(idea.getCreatedDate()),
                idea.getAuthor()
            });
        }
        
    }

    public String formatDate(Date date) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        return formatter.format(date);
    }

    private void setupTableTextWrap() {
        tblViewIdea.setDefaultRenderer(Object.class, new TableCellRenderer() {
            private final JTextArea textArea = new JTextArea();

            {
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setOpaque(true);
            }

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof ImageIcon) {
                    return new JLabel((ImageIcon) value);
                } else {
                    textArea.setText(value != null ? value.toString() : "");
                    textArea.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                    textArea.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
                    return textArea;
                }
            }
        });

        // Adjust row height to accommodate text area
        tblViewIdea.setRowHeight(150); // You might need to adjust this value

        // Apply the same renderer and row height to the feedback table
        tblViewFeedback.setDefaultRenderer(Object.class, new TableCellRenderer() {
            private final JTextArea textArea = new JTextArea();

            {
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setOpaque(true);
            }

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof ImageIcon) {
                    return new JLabel((ImageIcon) value);
                } else {
                    textArea.setText(value != null ? value.toString() : "");
                    textArea.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                    textArea.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
                    return textArea;
                }
            }
        });

        // Adjust row height for feedback table
        tblViewFeedback.setRowHeight(50); // You might need to adjust this value
    }

    public void populateFeedbackTable(int ideaId) {
        DefaultTableModel model = (DefaultTableModel) tblViewFeedback.getModel();
        model.setRowCount(0);

        for (Feedback feedback : business.getFeedbackDirectory().getFeedbackListByIdeaId(ideaId)) {
            model.addRow(new Object[]{
                feedback.getFeedId(),
                feedback.getAuthor(),
                feedback.getDetails(),
                formatDate(feedback.getDate())
            });
        }

        tblViewFeedback.setRowHeight(50);
    }

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {
        JTabbedPane tabSource = (JTabbedPane) evt.getSource();
        int selectedIndex = tabSource.getSelectedIndex();
        String selectedTabTitle = tabSource.getTitleAt(selectedIndex);

        if ("Blog".equals(selectedTabTitle)) {

            Feedbacks.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    innerTabbedPaneStateChanged(evt);
                }
            });
        }

    }

    private void innerTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {
        JTabbedPane tabSource = (JTabbedPane) evt.getSource();
        int selectedIndex = tabSource.getSelectedIndex();

        final int ADD_FEEDBACK_TAB_INDEX = 2;
        final int ADD_FEEDBACK_TAB_INDEX1 = 1;

        if (selectedIndex == ADD_FEEDBACK_TAB_INDEX) {
            if (tblViewIdea.getSelectedRow() != -1) {
                int ideaId = Integer.parseInt(tblViewIdea.getValueAt(tblViewIdea.getSelectedRow(), 0).toString());
                Idea idea = business.getIdeaDirectory().getIdeaById(ideaId);
                if (idea != null) {
                    txtTitle1.setText(idea.getTitle());
                    updateDescription1.setText(""); // Clear any previous text
                }
            }
        } else if (selectedIndex == ADD_FEEDBACK_TAB_INDEX1) {
            if (tblViewIdea.getSelectedRow() != -1) {
                int ideaId = Integer.parseInt(tblViewIdea.getValueAt(tblViewIdea.getSelectedRow(), 0).toString());
                Idea idea = business.getIdeaDirectory().getIdeaById(ideaId);
                if (idea != null) {
                    txtTitle.setText(idea.getTitle());
                    updateDescription.setText(idea.getDescription());
                    ideaImage = idea.getIdeaImage();
                    ideaImg.setIcon(new ImageIcon(ideaImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddAmount;
    private javax.swing.JPanel Blog;
    private javax.swing.JComboBox<String> ComboCategory;
    private javax.swing.JTabbedPane Feedbacks;
    private javax.swing.JLabel OfferedPrice;
    private javax.swing.JTextField TxtofferedPrice;
    private javax.swing.JTextField UpdateDescriptionmessage;
    private javax.swing.JPanel View;
    private javax.swing.JPanel ViewProducts;
    private javax.swing.JPanel ViewRequest;
    private javax.swing.JPanel add;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnGetFeedback;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane feedbackScroll1;
    private javax.swing.JLabel header;
    private javax.swing.JLabel ideaImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbProductID;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblAddbalance;
    private javax.swing.JLabel lblComments1;
    private javax.swing.JLabel lblExistingBalance;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblestimationPirce;
    private javax.swing.JLabel prodImg;
    private javax.swing.JTable tblView;
    private javax.swing.JTable tblViewFeedback;
    private javax.swing.JTable tblViewIdea;
    private javax.swing.JTextField txtActualPrice;
    private javax.swing.JTextField txtAddAmount;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtExistingBalance;
    private javax.swing.JTextField txtFarmersName;
    private javax.swing.JTextField txtFarmersUserName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMEssage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JButton txtReject;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtTitle1;
    private javax.swing.JTextField txtUserNamewallet;
    private javax.swing.JTextField updateDescription;
    private javax.swing.JTextField updateDescription1;
    // End of variables declaration//GEN-END:variables
}
