/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customerRole;

import business.Business;
import business.customer.Order;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAccount.UserAccount;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhavanidevulapalli
 */
public class CustomerDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDashboardJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Business business;
    private Network network;
   private Enterprise enterprise;
    private WorkRequest request;
    

    
    public CustomerDashboardJPanel(JPanel userProcessContainer, UserAccount account, Business business, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account = account;
        this.business = business;
        this.network = network;
        this.enterprise = enterprise;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnManageProduct1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnWalletAction = new javax.swing.JButton();
        Review = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        header.setFont(new java.awt.Font("Khmer MN", 1, 36)); // NOI18N
        header.setForeground(new java.awt.Color(255, 102, 51));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-return-purchase-80.png"))); // NOI18N
        header.setText("Welcome to Online Shopping Store");

        btnAddProduct.setBackground(new java.awt.Color(255, 255, 102));
        btnAddProduct.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/viewproducts.png"))); // NOI18N
        btnAddProduct.setText("Fresh2Home Products");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnManageProduct1.setBackground(new java.awt.Color(255, 255, 102));
        btnManageProduct1.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnManageProduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-create-order-30.png"))); // NOI18N
        btnManageProduct1.setText("Order History");
        btnManageProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProduct1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/FreshVegetables-ezgif.com-resize.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Khmer MN", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("** All our products underwent quality check and certified by specialists **");

        btnWalletAction.setBackground(new java.awt.Color(255, 255, 102));
        btnWalletAction.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        btnWalletAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-add-dollar-40.png"))); // NOI18N
        btnWalletAction.setText("Load Wallet");
        btnWalletAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWalletActionActionPerformed(evt);
            }
        });

        Review.setBackground(new java.awt.Color(255, 255, 102));
        Review.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        Review.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-add-dollar-40.png"))); // NOI18N
        Review.setText("Review");
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 2060, Short.MAX_VALUE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWalletAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Review, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnManageProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnWalletAction, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Review, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:

        ViewCertifiedProductsJPanel panel = new ViewCertifiedProductsJPanel(userProcessContainer, account, business, network, enterprise);
        userProcessContainer.add("ViewCertifiedProductsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnManageProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProduct1ActionPerformed
        // TODO add your handling code here:
        
        OrderSummaryJPanel panel = new OrderSummaryJPanel(userProcessContainer, account, business);
        userProcessContainer.add("OrderSummary", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProduct1ActionPerformed

    private void btnWalletActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWalletActionActionPerformed
        // TODO add your handling code here:
        WalletJPanel panel = new WalletJPanel(userProcessContainer, account, business,network,enterprise);
        userProcessContainer.add("Wallet", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWalletActionActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        // TODO add your handling code here:
        CustomerFeedbackJPanel panel = new CustomerFeedbackJPanel(userProcessContainer, account, business,network,enterprise);
        userProcessContainer.add("CustomerFeedback", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Review;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnManageProduct1;
    private javax.swing.JButton btnWalletAction;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
