/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.Business;
import business.ConfigureASystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harshitha
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private Business business;
    private ConfigureASystem configureASystem;

    private JPanel userProcessContainer;
    private UserAccount account;
    private Network network;
    private Enterprise enterprise;

    LoginJPanel(JPanel userProcessContainer, UserAccount account, Business business, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;

        this.network = network;
        this.enterprise = enterprise;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JPasswordField();
        chkbox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernameError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 113, 178));

        jLabel4.setFont(new java.awt.Font("Khmer MN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 235, 246));
        jLabel4.setText("LOGIN SCREEN");

        jLabel1.setBackground(new java.awt.Color(202, 224, 240));
        jLabel1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 224, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/username.png"))); // NOI18N
        jLabel1.setText("User Name");

        txtLoginUsername.setBackground(new java.awt.Color(202, 224, 240));
        txtLoginUsername.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        txtLoginUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 91, 190)));
        txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsernameActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(202, 224, 240));
        jLabel3.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(202, 224, 240));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/password.png"))); // NOI18N
        jLabel3.setText("   Password");

        txtLoginPassword.setBackground(new java.awt.Color(204, 224, 240));
        txtLoginPassword.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        txtLoginPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 91, 190)));

        chkbox.setBackground(new java.awt.Color(0, 113, 178));
        chkbox.setFont(new java.awt.Font("Khmer MN", 0, 13)); // NOI18N
        chkbox.setForeground(new java.awt.Color(202, 224, 240));
        chkbox.setText("Show Password");
        chkbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/showpassword.png"))); // NOI18N
        chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 91, 191));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/ORGANIC FARMING.png"))); // NOI18N

        usernameError.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        usernameError.setForeground(new java.awt.Color(204, 0, 0));
        usernameError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        passwordError.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        passwordError.setForeground(new java.awt.Color(204, 0, 0));
        passwordError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(202, 224, 240));
        jLabel5.setText("Dont have an account?");

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setFont(new java.awt.Font("Khmer MN", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 91, 191));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8-register-30.png"))); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(usernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkbox, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(passwordError, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbox)
                .addGap(4, 4, 4)
                .addComponent(usernameError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(150, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxActionPerformed
        // TODO add your handling code here:
        if (chkbox.isSelected()) {
            txtLoginPassword.setEchoChar((char) 0);
        } else {
            txtLoginPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxActionPerformed

    private void jButton1LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginButtonActionPerformed
        // TODO add your handling code here:
        String userName = txtLoginUsername.getText();
        String password = txtLoginPassword.getText();
        boolean isUserFound = false;

        if (userName.equals("")) {
            usernameError.setText("Enter the user name");
        } else {
            usernameError.setText(""); // Clear any previous error messages
        }

        if (password.equals("")) {
            passwordError.setText("Enter the password");
        } else {
            passwordError.setText(""); // Clear any previous error messages
        }

     
        Enterprise inEnterprise = null;
        Organization inOrganisation = null;
        Network choosenNetwork = null;
        UserAccount userAccount = business.getUserAccountDirectory().authenticateUser(userName, password);
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : business.getNetworkList()) {
                System.out.println("I am in network" + network);
                //Step 2-a: Check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    System.out.println("I am in enterprise" + enterprise);
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        //Step3: Check against each organization inside that enterprise

                        for (Organization organisation : enterprise.getOrganizationDirectory().getOrganisationList()) {
                            System.out.println("I am in organisation" + organisation);
                            userAccount = organisation.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                System.out.println("the user account is found");
                                inEnterprise = enterprise;
                                inOrganisation = organisation;
                                choosenNetwork = network;
                                break;
                            }
                        }
                    } else {
                        inEnterprise = enterprise;
                        break;
                    }
                    if (inOrganisation != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
                if (userAccount != null) {
                    choosenNetwork = network;
                    break;
                }
            }
        } else {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            try {
                System.out.println(userAccount.getRole());
                userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, business, choosenNetwork, inEnterprise));
                layout.next(userProcessContainer);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        if (!userName.isEmpty() && !password.isEmpty() && userAccount == null) {
            usernameError.setText("Invalid username or password");
        }

    }//GEN-LAST:event_jButton1LoginButtonActionPerformed

    private void jButton2LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LoginButtonActionPerformed
        // TODO add your handling code here:
        RegisterJPanelCustomer panel = new RegisterJPanelCustomer(userProcessContainer, account, business, network, enterprise);
        userProcessContainer.add("RegisterJPanelCustomer", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2LoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel passwordError;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JLabel usernameError;
    // End of variables declaration//GEN-END:variables
}
